# coding: utf-8

"""
    QUBO API solvers

    QUBO solvers from Meta Analytics  # noqa: E501

    OpenAPI spec version: v1
    Contact: rajesh@craftingdata.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import alphaqubo_client
from models.points import Points  # noqa: E501
from alphaqubo_client.rest import ApiException


class TestPoints(unittest.TestCase):
    """Points unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPoints(self):
        """Test Points"""
        # FIXME: construct object with mandatory attributes with example values
        # model = alphaqubo_client.models.points.Points()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
