# coding: utf-8

"""
    QUBO API solvers

    QUBO solvers from Meta Analytics  # noqa: E501

    OpenAPI spec version: v1
    Contact: rajesh@craftingdata.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "alphaqubo-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil", "dimod", "jupyter", "scipy", "boto3"]

setup(
    name=NAME,
    version=VERSION,
    description="QUBO API solvers",
    author_email="rajesh@craftingdata.com",
    url="",
    keywords=["Swagger", "QUBO API solvers"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    QUBO solvers from Meta Analytics  # noqa: E501
    """
)
